name: "Bug report"
description: "Report a bug in the Elastic Security documentation"
title: "[BUG] "
labels: "bug"
body: 
  - type: markdown
    attributes:
      value: |
        Hello! Use this form to alert the [@elastic/security-docs](https://github.com/orgs/elastic/teams/security-docs) team to a documentation bug.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug. What needs to be removed, edited, added, or replaced?
    validations:
      required: true
  - type: dropdown
    id: doc-set
    attributes:
      label: Which documentation set(s) include this bug?
      description: ESS (classic), serverless, or both?
      options:
        - ESS and serverless
        - ESS only
        - Serverless only
        - Unknown
      default: 0
    validations:
      required: true
  - type: textarea
    id: doc-links
    attributes:
      label: Documentation links
      description: Which docs are affected?
      placeholder: |
        E.g. https://www.elastic.co/guide/en/security/current/es-overview.html
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Bug reproduction instructions
      description: If this bug is related to part of Elastic Security, such as a screenshot that is no longer accurate, please tell us how to reproduce the relevant software state. If applicable, provide testing environment information, or steps to generate necessary data.
      placeholder: |
        E.g. Go to the Alerts page. Make sure there are at least 10 alerts. Open the Fields menu and you'll see... 
    validations:
      required: true
